User dshboard backend
harshraj22/contest pull request #37
Opened 2019-10-05 05:29 UTC by harshraj22

Updated user dashboard backend
For reviewers :
- [ ] update your login.php (add your own user name and password, database = "cse_hub" , hostname = "localhost")

- [ ] Update your practice_questions_info table (
 +-----------+------------------+---------------------------------+------------------------+---------+
| ques_ID | date_created | successful_submissions | total_submissions | admin |
+-----------+-------------------+---------------------------------+------------------------+----------+
| q1           | NULL             |                      0                |                 0           | super  |
+------------+------------------+---------------------------------+------------------------+---------+

- [ ] update your user_info table
+-------------+-----------------------+--------+
| username | email                  | name |
+--------------+------------------- --+-------+
| user          | user@user.com | user   |
+-------------+----------------------+---------+

* Front end hasn't been updated, so for now go to al.html
* try logging in using usernames that exist and that doesn't 
* try links given and report any vulnerability
* try to directly access dashboard.php ( in this case, dashboard.php doesn't have info regarding whose dashboard to display )

2019-10-06 00:50 UTC, JanhaviDadhania commented on CSE-Hub/user/dashboard.php
> +                        for($i = 0;$i<$newNumOfRows;$i++){
$newRow = mysqli_fetch_row($newResult);
this line should be added here.

2019-10-06 00:53 UTC, JanhaviDadhania reviewed
on dashboard it displays only first row of practice questions info table. 
if multiple rows are present in table then it displays same row multiple times.

2019-10-06 00:58 UTC, JanhaviDadhania requested changes
$newRow = mysqli_fetch_row($newResult);
this line should be added inside for loop.

2019-10-06 08:09 UTC, harshraj22 commented
> $newRow = mysqli_fetch_row($newResult);
> this line should be added inside for loop.

Updated :+1:

2019-10-10 16:53 UTC, harshraj22 commented
Current features:
* Shows 10 practice questions in the right pannel (has option to sort based on number of successful submissions, date created)
* Each of these is link which displays the actual question (now shows directly .txt file)
* Has a link that shows all the questions, which contains link for each questions (when clicked shows those .txt files).

To do:
* Add user submissions link.

2019-10-10 18:18 UTC, DestroyerAlpha commented
Small change:
Error 4040 -> Error 404

2019-10-11 13:24 UTC, harshraj22 commented
Updated to add user submissions page linked to user  dashboard. Fetches all details directly form user solutions table.
#45

2019-10-12 13:00 UTC, JanhaviDadhania commented on CSE-Hub/user/dashboard.php
> +    echo $newQuery;
shouldn't this be commented?

2019-10-13 05:39 UTC, harshraj22 commented on CSE-Hub/user/dashboard.php
> +    echo $newQuery;
updated

2019-10-15 22:13 UTC, DestroyerAlpha commented
So you have just designed the basic user submissions page right? Because it needs some spice :100: 
Like adding some border to the tables.

2019-10-16 13:10 UTC, harshraj22 commented
Yeah, this wasn't aimed for frontend.

2019-10-16 13:11 UTC, merged